package model

import (
	"gorm.io/gorm"
)

// LocalPublicFund 地単公費マスタ
// doc/kouhi/chitankouhi_koumoku_240329.pdf に基づく定義
type LocalPublicFund struct {
	gorm.Model
	OfficialName                  string `gorm:"comment:1:事業名の正式名称"`
	AbbreviatedName               string `gorm:"comment:2:事業名(略称)"`
	PrefectureCode                string `gorm:"index;comment:3:都道府県コード"`
	MunicipalityCode              string `gorm:"index;comment:4:市区町村コード"`
	ClassificationNumber1         string `gorm:"comment:5:分類番号1"`
	ClassificationNumber2         string `gorm:"comment:6:分類番号2"`
	ClassificationNumber3         string `gorm:"comment:7:分類番号3"`
	PayerNumber8                  string `gorm:"index;comment:8:公費負担者番号(8桁)"`
	PayerNumberOther              string `gorm:"index;comment:9:公費負担者番号(8桁以外)"`
	IntraProjectCategoryCode      int    `gorm:"comment:10:事業内区分コード"`
	EffectiveStartDate            string `gorm:"comment:11:有効開始年月日"`
	EffectiveEndDate              string `gorm:"comment:12:有効終了年月日"`
	AgeCriteriaAbove              int    `gorm:"comment:13:年齢基準(以上)"`
	TargetAgeAbove                int    `gorm:"comment:14:対象年齢(以上)"`
	AgeCriteriaBelow              int    `gorm:"comment:15:年齢基準(未満)"`
	TargetAgeBelow                int    `gorm:"comment:16:対象年齢(未満)"`
	ApplicableMedicalInpatient    bool   `gorm:"comment:17:医科入院"`
	ApplicableMedicalOutpatient   bool   `gorm:"comment:18:医科外来"`
	ApplicableDentalInpatient     bool   `gorm:"comment:19:歯科入院"`
	ApplicableDentalOutpatient    bool   `gorm:"comment:20:歯科外来"`
	ApplicablePharmacy            bool   `gorm:"comment:21:調剤"`
	ApplicableVisitingNursing     bool   `gorm:"comment:22:訪問看護"`
	ApplicableBoneSetter          bool   `gorm:"comment:23:柔整"`
	ApplicableAcupuncture         bool   `gorm:"comment:24:あはき"`
	PrerequisitePublicFundSystem  string `gorm:"comment:25:所持が前提となる公費負担医療の制度別番号"`
	IncomeCategory                string `gorm:"comment:26:所得区分"`
	IncomeLowerLimit              int    `gorm:"comment:27:対象者の所得金額(下限)"`
	IncomeUpperLimit              int    `gorm:"comment:28:対象者の所得金額(上限)"`
	SchoolingStatus               int    `gorm:"comment:29:就学状況"`
	MultiChildHousehold           int    `gorm:"comment:30:多子世帯設定"`
	ChildCountCondition           int    `gorm:"comment:31:子ども人数"`
	ChildOrderCondition           int    `gorm:"comment:32:何人目か"`
	ScopeCombinationFlag          int    `gorm:"comment:33:対象範囲(2)複数選択フラグ"`
	ScopeAndConditions            string `gorm:"comment:34:対象範囲(2)AND条件"`
	ScopeOrConditions             string `gorm:"comment:35:対象範囲(2)OR条件"`
	BenefitMethod                 int    `gorm:"comment:36:助成方法"`
	CommissionAgencyFlag          int    `gorm:"comment:37:委託有無"`
	CommissionFund                int    `gorm:"comment:38:社会保険診療報酬支払基金への委託"`
	CommissionAssociation         int    `gorm:"comment:39:国民健康保険団体連合会への委託"`
	ConditionSpecifyFlag          int    `gorm:"comment:40:助成条件・自己負担条件指定"`
	FirstVisitCondition           int    `gorm:"comment:41:初診時のみ条件"`
	FirstInpatientCondition       int    `gorm:"comment:42:入院初回時のみ条件"`
	ContinuousInpatientMonths     int    `gorm:"comment:43:連続入院条件(月数)"`
	SameMedicalOrgInpatient       int    `gorm:"comment:44:同一医療機関等の要件(入院)"`
	MultipleVisitCount            int    `gorm:"comment:45:複数回受診条件(回数)"`
	SameMedicalOrgOutpatient      int    `gorm:"comment:46:同一医療機関等の要件(外来)"`
	InsuranceChangeAccumulation   int    `gorm:"comment:47:保険制度変更前の患者負担額の累計"`
	BenefitPatternInpatient       int    `gorm:"comment:48:助成パターン(入院)"`
	FixedAmountInpatient          int    `gorm:"comment:49:固定額(入院)"`
	RatioInpatient                int    `gorm:"comment:50:割合(入院)"`
	BenefitPatternOutpatient      int    `gorm:"comment:51:助成パターン(外来)"`
	FixedAmountOutpatient         int    `gorm:"comment:52:固定額(外来)"`
	RatioOutpatient               int    `gorm:"comment:53:割合(外来)"`
	CapTypeIdentifier             int    `gorm:"comment:54:上限額識別フラグ"`
	SingleParentIdentifier        int    `gorm:"comment:55:ひとり親等医療費助成対象者識別フラグ"`
	CapInpatientOutpatientMerged  int    `gorm:"comment:56:上限額入院外来合算フラグ"`
	SameMedicalOrgCap             int    `gorm:"comment:57:自己負担上限額における同一医療機関等の要件"`
	PharmacyBurdenUnderCap        int    `gorm:"comment:58:外来受診時の調剤薬局での自己負担の有無"`
	CapInpatientDaily             int    `gorm:"comment:59:1日当たりの上限額(入院)"`
	CapInpatientDailyLimitDays    int    `gorm:"comment:60:1日当たりの上限額の適用上限日数(入院)"`
	CapInpatientWeekly            int    `gorm:"comment:61:1週当たりの上限額(入院)"`
	CapInpatientReceipt           int    `gorm:"comment:62:1レセプト当たりの上限額(入院)"`
	CapInpatientMonthly           int    `gorm:"comment:63:1月当たりの上限額(入院)"`
	CapInpatientYearly            int    `gorm:"comment:64:1年当たりの上限額(入院)"`
	CapOutpatientPerVisit         int    `gorm:"comment:65:1回当たりの上限額(外来)"`
	CapOutpatientVisitLimit       int    `gorm:"comment:66:1回当たりの上限額の適用上限回数(外来)"`
	CapOutpatientDaily            int    `gorm:"comment:67:1日当たりの上限額(外来)"`
	CapOutpatientDailyLimitDays   int    `gorm:"comment:68:1日当たりの上限額の適用上限日数(外来)"`
	CapOutpatientWeekly           int    `gorm:"comment:69:1週当たりの上限額(外来)"`
	CapOutpatientReceipt          int    `gorm:"comment:70:1レセプト当たりの上限額(外来)"`
	CapOutpatientMonthly          int    `gorm:"comment:71:1月当たりの上限額(外来)"`
	CapOutpatientYearly           int    `gorm:"comment:72:1年当たりの上限額(外来)"`
	CapFoodDaily                  int    `gorm:"comment:73:1日当たりの上限額(食事)"`
	CapFoodWeekly                 int    `gorm:"comment:74:1週当たりの上限額(食事)"`
	CapFoodMonthly                int    `gorm:"comment:75:1月当たりの上限額(食事)"`
	CapFoodYearly                 int    `gorm:"comment:76:1年当たりの上限額(食事)"`
	CapLivingDaily                int    `gorm:"comment:77:1日当たりの上限額(生活)"`
	CapLivingWeekly               int    `gorm:"comment:78:1週当たりの上限額(生活)"`
	CapLivingMonthly              int    `gorm:"comment:79:1月当たりの上限額(生活)"`
	CapLivingYearly               int    `gorm:"comment:80:1年当たりの上限額(生活)"`
	BenefitOtherPublicFundBurden  int    `gorm:"comment:81:他公費負担医療の自己負担額を助成するか"`
	BenefitOtherFundPattern       int    `gorm:"comment:82:他公費助成パターン"`
	BenefitOtherFundFixedAmount   int    `gorm:"comment:83:他公費助成固定額"`
	BenefitOtherFundRatio         int    `gorm:"comment:84:他公費助成割合"`
	TargetSystemNumber1           string `gorm:"comment:85:特定の公費対象1"`
	TargetSystemNumber2           string `gorm:"comment:86:特定の公費対象2"`
	TargetSystemNumber3           string `gorm:"comment:87:特定の公費対象3"`
	HasInterOrgCapManagementBook  int    `gorm:"comment:88:医療機関を跨ぐ患者自己負担上限管理票の有無"`
	InterOrgCapAmount             int    `gorm:"comment:89:上限管理票の上限額"`
	InterOrgCapUnit               int    `gorm:"comment:90:上限管理票の上限単位"`
	InterOrgCapTarget             int    `gorm:"comment:91:上限管理票の対象(個人/世帯)"`
	HighMedicalExpenseCalculation int    `gorm:"comment:92:高額療養費計算の対象"`
	LocalFundPriority             int    `gorm:"comment:93:公費適用優先順位"`
	DesignatedMedicalOrgOnly      int    `gorm:"comment:94:指定医療機関のみ"`
	ElderlySupportApplicability   int    `gorm:"comment:95:後期高齢者配慮措置の対象"`
	ReceiptSpecialNoteNumber      string `gorm:"comment:96:レセプト特記事項番号"`
	ReceiptSpecialNoteText        string `gorm:"comment:97:レセプト特記事項名称"`
	ReceiptCommentCode            string `gorm:"comment:98:レセプトコメントコード"`
	OtherNotes                    string `gorm:"comment:99:その他注釈"`
}
