// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Comment defines model for Comment.
type Comment struct {
	// Category 3: 区分 ('8'固定)
	Category *string `json:"category,omitempty"`

	// Code 23: コメントコード (9桁)
	Code      *string    `json:"code,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// DiscontinuedDate 22: 廃止年月日 (YYYYMMDD)
	DiscontinuedDate *string `json:"discontinued_date,omitempty"`

	// Id DB内のユニークID
	Id *int `json:"id,omitempty"`

	// MasterType 2: マスター種別 ('C'固定)
	MasterType *string `json:"master_type,omitempty"`

	// NameKana 9: カナ名称
	NameKana *string `json:"name_kana,omitempty"`

	// NameKanaLen 8: カナ有効桁数
	NameKanaLen *int `json:"name_kana_len,omitempty"`

	// NameKanji 7: 漢字名称
	NameKanji *string `json:"name_kanji,omitempty"`

	// NameKanjiLen 6: 漢字有効桁数
	NameKanjiLen *int `json:"name_kanji_len,omitempty"`

	// Pattern 4: パターン
	Pattern *string `json:"pattern,omitempty"`

	// PublishOrder 24: 公表順序番号
	PublishOrder *int `json:"publish_order,omitempty"`

	// ReceiptEditInfo1Len 11: ①桁数
	ReceiptEditInfo1Len *int `json:"receipt_edit_info_1_len,omitempty"`

	// ReceiptEditInfo1Pos 10: ①カラム位置
	ReceiptEditInfo1Pos *int `json:"receipt_edit_info_1_pos,omitempty"`

	// ReceiptEditInfo2Len 13: ②桁数
	ReceiptEditInfo2Len *int `json:"receipt_edit_info_2_len,omitempty"`

	// ReceiptEditInfo2Pos 12: ②カラム位置
	ReceiptEditInfo2Pos *int `json:"receipt_edit_info_2_pos,omitempty"`

	// ReceiptEditInfo3Len 15: ③桁数
	ReceiptEditInfo3Len *int `json:"receipt_edit_info_3_len,omitempty"`

	// ReceiptEditInfo3Pos 14: ③カラム位置
	ReceiptEditInfo3Pos *int `json:"receipt_edit_info_3_pos,omitempty"`

	// ReceiptEditInfo4Len 17: ④桁数
	ReceiptEditInfo4Len *int `json:"receipt_edit_info_4_len,omitempty"`

	// ReceiptEditInfo4Pos 16: ④カラム位置
	ReceiptEditInfo4Pos *int `json:"receipt_edit_info_4_pos,omitempty"`

	// Reserved1 18: 予備
	Reserved1 *string `json:"reserved_1,omitempty"`

	// Reserved2 19: 予備
	Reserved2 *string `json:"reserved_2,omitempty"`

	// Reserved3 25: 予備
	Reserved3 *string `json:"reserved_3,omitempty"`

	// Reserved4 26: 予備
	Reserved4 *string `json:"reserved_4,omitempty"`

	// Reserved5 27: 予備
	Reserved5 *string `json:"reserved_5,omitempty"`

	// Reserved6 28: 予備
	Reserved6 *string `json:"reserved_6,omitempty"`

	// Reserved7 29: 予備
	Reserved7 *string `json:"reserved_7,omitempty"`

	// Reserved8 30: 予備
	Reserved8 *string `json:"reserved_8,omitempty"`

	// SelectionCategory 20: 選択式コメント識別
	SelectionCategory *string `json:"selection_category,omitempty"`

	// SerialNo 5: 一連番号
	SerialNo *string `json:"serial_no,omitempty"`

	// UpdateCategory 1: 変更区分 (0:無変更, 1:抹消, 3:新規, 5:変更, 9:廃止)
	UpdateCategory *string `json:"update_category,omitempty"`

	// UpdateDate 21: 変更年月日 (YYYYMMDD)
	UpdateDate *string    `json:"update_date,omitempty"`
	UpdatedAt  *time.Time `json:"updated_at,omitempty"`
}

// CommentRelation defines model for CommentRelation.
type CommentRelation struct {
	ActCode             *string    `json:"act_code,omitempty"`
	ActNameAbbr         *string    `json:"act_name_abbr,omitempty"`
	AdditionCode        *string    `json:"addition_code,omitempty"`
	AdmissionCategory   *string    `json:"admission_category,omitempty"`
	BranchNumber        *string    `json:"branch_number,omitempty"`
	CalculateCount      *int       `json:"calculate_count,omitempty"`
	CommentCode         *string    `json:"comment_code,omitempty"`
	CommentText         *string    `json:"comment_text,omitempty"`
	ConditionCategory   *string    `json:"condition_category,omitempty"`
	CreatedAtRel        *time.Time `json:"created_at_rel,omitempty"`
	DiscontinuedDateRel *string    `json:"discontinued_date_rel,omitempty"`
	Id                  *int       `json:"id,omitempty"`
	ItemNumber          *string    `json:"item_number,omitempty"`
	NonPaymentReason    *string    `json:"non_payment_reason,omitempty"`
	NotificationType    *string    `json:"notification_type,omitempty"`
	PatientStatusCode   *string    `json:"patient_status_code,omitempty"`
	PublishOrderRel     *string    `json:"publish_order_rel,omitempty"`
	Section             *string    `json:"section,omitempty"`
	UpdateCategory      *string    `json:"update_category,omitempty"`
	UpdateDateRel       *string    `json:"update_date_rel,omitempty"`
	UpdatedAtRel        *time.Time `json:"updated_at_rel,omitempty"`
}

// Disease defines model for Disease.
type Disease struct {
	// AdoptionCategory 12: 採択区分
	AdoptionCategory   *string `json:"adoption_category,omitempty"`
	AdoptionUpdateFlag *string `json:"adoption_update_flag,omitempty"`

	// Code 3: 傷病名コード
	Code                          *string    `json:"code,omitempty"`
	CreatedAt                     *time.Time `json:"created_at,omitempty"`
	DentalNameAbbr                *string    `json:"dental_name_abbr,omitempty"`
	DentalNameAbbrLen             *int       `json:"dental_name_abbr_len,omitempty"`
	DentalNameAbbrUpdateFlag      *string    `json:"dental_name_abbr_update_flag,omitempty"`
	DentalSpecificDiseaseCategory *string    `json:"dental_specific_disease_category,omitempty"`
	DentalSpecificUpdateFlag      *string    `json:"dental_specific_update_flag,omitempty"`

	// DiscontinuedDate 24: 廃止年月日
	DiscontinuedDate *string `json:"discontinued_date,omitempty"`

	// DiseaseExchangeCode 13: 病名交換用コード
	DiseaseExchangeCode       *string `json:"disease_exchange_code,omitempty"`
	DiseaseExchangeUpdateFlag *string `json:"disease_exchange_update_flag,omitempty"`

	// DiseaseManagementNumber 11: 病名管理番号
	DiseaseManagementNumber *string `json:"disease_management_number,omitempty"`

	// Icd101 16: ICD-10-1
	Icd101           *string `json:"icd10_1,omitempty"`
	Icd101UpdateFlag *string `json:"icd10_1_update_flag,omitempty"`

	// Icd102 17: ICD-10-2
	Icd102           *string `json:"icd10_2,omitempty"`
	Icd102UpdateFlag *string `json:"icd10_2_update_flag,omitempty"`
	Id               *int    `json:"id,omitempty"`

	// ImportDate 22: 収載年月日
	ImportDate                 *string `json:"import_date,omitempty"`
	IncurableDiseaseCategory   *string `json:"incurable_disease_category,omitempty"`
	IncurableDiseaseUpdateFlag *string `json:"incurable_disease_update_flag,omitempty"`

	// InsuranceOutCategory 20: 保険請求外区分
	InsuranceOutCategory   *string `json:"insurance_out_category,omitempty"`
	InsuranceOutUpdateFlag *string `json:"insurance_out_update_flag,omitempty"`

	// IsOld 旧傷病名管理ファイル由来の場合true
	IsOld *bool `json:"is_old,omitempty"`

	// MasterType 2: マスター種別
	MasterType *string `json:"master_type,omitempty"`

	// MigrationManagementNumber 38: 移行先病名管理番号
	MigrationManagementNumber *string  `json:"migration_management_number,omitempty"`
	MigrationTarget           *Disease `json:"migration_target,omitempty"`

	// NameAbbr 8: 傷病名省略名称
	NameAbbr *string `json:"name_abbr,omitempty"`

	// NameAbbrLen 7: 傷病名省略名称桁数
	NameAbbrLen        *int    `json:"name_abbr_len,omitempty"`
	NameAbbrUpdateFlag *string `json:"name_abbr_update_flag,omitempty"`

	// NameKana 10: 傷病名カナ名称
	NameKana *string `json:"name_kana,omitempty"`

	// NameKanaLen 9: 傷病名カナ名称桁数
	NameKanaLen        *int    `json:"name_kana_len,omitempty"`
	NameKanaUpdateFlag *string `json:"name_kana_update_flag,omitempty"`

	// NameKanji 6: 傷病名基本名称
	NameKanji *string `json:"name_kanji,omitempty"`

	// NameKanjiLen 5: 傷病名基本名称桁数
	NameKanjiLen        *int    `json:"name_kanji_len,omitempty"`
	NameKanjiUpdateFlag *string `json:"name_kanji_update_flag,omitempty"`

	// RelatedCode 4: 移行先コード
	RelatedCode *string `json:"related_code,omitempty"`

	// Reserved1 14: 予備
	Reserved1 *string `json:"reserved_1,omitempty"`

	// Reserved2 15: 予備
	Reserved2 *string `json:"reserved_2,omitempty"`

	// Reserved3 18: 予備
	Reserved3 *string `json:"reserved_3,omitempty"`
	Reserved4 *string `json:"reserved_4,omitempty"`
	Reserved5 *string `json:"reserved_5,omitempty"`
	Reserved6 *string `json:"reserved_6,omitempty"`
	Reserved7 *string `json:"reserved_7,omitempty"`

	// SingleUseForbiddenCategory 19: 単独使用禁止区分
	SingleUseForbiddenCategory   *string `json:"single_use_forbidden_category,omitempty"`
	SingleUseForbiddenUpdateFlag *string `json:"single_use_forbidden_update_flag,omitempty"`

	// SpecificDiseaseCategory 21: 特定疾患等対象区分
	SpecificDiseaseCategory   *string `json:"specific_disease_category,omitempty"`
	SpecificDiseaseUpdateFlag *string `json:"specific_disease_update_flag,omitempty"`

	// UpdateCategory 1: 変更区分
	UpdateCategory *string `json:"update_category,omitempty"`

	// UpdateDate 23: 変更年月日
	UpdateDate *string    `json:"update_date,omitempty"`
	UpdatedAt  *time.Time `json:"updated_at,omitempty"`
}

// Medication defines model for Medication.
type Medication struct {
	AgeAdditionCategory *string `json:"age_addition_category,omitempty"`

	// Code 3: 調剤行為コード
	Code             *string    `json:"code,omitempty"`
	CreatedAt        *time.Time `json:"created_at,omitempty"`
	DiscontinuedDate *string    `json:"discontinued_date,omitempty"`
	Id               *int       `json:"id,omitempty"`
	ImportDate       *string    `json:"import_date,omitempty"`

	// MasterType 2: マスター種別
	MasterType                 *string `json:"master_type,omitempty"`
	MaxAge                     *string `json:"max_age,omitempty"`
	MaxPoints                  *int    `json:"max_points,omitempty"`
	MaxPriceFlag               *string `json:"max_price_flag,omitempty"`
	MedicationManagementNumber *string `json:"medication_management_number,omitempty"`
	MedicationMigrationFlag    *string `json:"medication_migration_flag,omitempty"`
	MedicationMigrationNumber  *string `json:"medication_migration_number,omitempty"`
	MedicationMigrationUpdate  *string `json:"medication_migration_update,omitempty"`
	MedicationSectionNumber    *string `json:"medication_section_number,omitempty"`
	MinAge                     *string `json:"min_age,omitempty"`

	// NameKana 7: カナ名称
	NameKana *string `json:"name_kana,omitempty"`

	// NameKanaLen 6: カナ有効桁数
	NameKanaLen        *int    `json:"name_kana_len,omitempty"`
	NameKanaUpdateFlag *string `json:"name_kana_update_flag,omitempty"`

	// NameKanji 5: 漢字名称
	NameKanji *string `json:"name_kanji,omitempty"`

	// NameKanjiLen 4: 漢字有効桁数
	NameKanjiLen        *int     `json:"name_kanji_len,omitempty"`
	NameKanjiUpdateFlag *string  `json:"name_kanji_update_flag,omitempty"`
	OldPrice            *float32 `json:"old_price,omitempty"`
	OldPriceType        *string  `json:"old_price_type,omitempty"`
	Price               *float32 `json:"price,omitempty"`
	PriceTablePrice     *float32 `json:"price_table_price,omitempty"`
	PriceType           *string  `json:"price_type,omitempty"`
	PublishOrder        *int     `json:"publish_order,omitempty"`
	RelatedCode         *string  `json:"related_code,omitempty"`
	Reserved1           *string  `json:"reserved_1,omitempty"`
	Reserved10          *string  `json:"reserved_10,omitempty"`
	Reserved11          *string  `json:"reserved_11,omitempty"`
	Reserved12          *string  `json:"reserved_12,omitempty"`
	Reserved13          *string  `json:"reserved_13,omitempty"`
	Reserved14          *string  `json:"reserved_14,omitempty"`
	Reserved15          *string  `json:"reserved_15,omitempty"`
	Reserved16          *string  `json:"reserved_16,omitempty"`
	Reserved17          *string  `json:"reserved_17,omitempty"`
	Reserved18          *string  `json:"reserved_18,omitempty"`
	Reserved19          *string  `json:"reserved_19,omitempty"`
	Reserved2           *string  `json:"reserved_2,omitempty"`
	Reserved20          *string  `json:"reserved_20,omitempty"`
	Reserved21          *string  `json:"reserved_21,omitempty"`
	Reserved22          *string  `json:"reserved_22,omitempty"`
	Reserved23          *string  `json:"reserved_23,omitempty"`
	Reserved24          *string  `json:"reserved_24,omitempty"`
	Reserved25          *string  `json:"reserved_25,omitempty"`
	Reserved26          *string  `json:"reserved_26,omitempty"`
	Reserved27          *string  `json:"reserved_27,omitempty"`
	Reserved28          *string  `json:"reserved_28,omitempty"`
	Reserved29          *string  `json:"reserved_29,omitempty"`
	Reserved3           *string  `json:"reserved_3,omitempty"`
	Reserved30          *string  `json:"reserved_30,omitempty"`
	Reserved31          *string  `json:"reserved_31,omitempty"`
	Reserved32          *string  `json:"reserved_32,omitempty"`
	Reserved4           *string  `json:"reserved_4,omitempty"`
	Reserved5           *string  `json:"reserved_5,omitempty"`
	Reserved6           *string  `json:"reserved_6,omitempty"`
	Reserved7           *string  `json:"reserved_7,omitempty"`
	Reserved8           *string  `json:"reserved_8,omitempty"`
	Reserved9           *string  `json:"reserved_9,omitempty"`
	TransitionalDate    *string  `json:"transitional_date,omitempty"`
	UnitCode            *string  `json:"unit_code,omitempty"`
	UnitNameKanji       *string  `json:"unit_name_kanji,omitempty"`
	UnitNameKanjiLen    *int     `json:"unit_name_kanji_len,omitempty"`

	// UpdateCategory 1: 変更区分
	UpdateCategory *string    `json:"update_category,omitempty"`
	UpdateDate     *string    `json:"update_date,omitempty"`
	UpdatedAt      *time.Time `json:"updated_at,omitempty"`
}

// SpecialMedicalDevice defines model for SpecialMedicalDevice.
type SpecialMedicalDevice struct {
	// AgeAdditionCategory 14: 年齢加算区分
	AgeAdditionCategory *string `json:"age_addition_category,omitempty"`

	// AppendixNumber 31: 別表番号
	AppendixNumber *string `json:"appendix_number,omitempty"`

	// Code 3: 特定器材コード (9桁)
	Code      *string    `json:"code,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// DeviceCategory 22: 特定器材種別
	DeviceCategory *string `json:"device_category,omitempty"`

	// DiscontinuedDate 30: 廃止年月日 (YYYYMMDD)
	DiscontinuedDate *string `json:"discontinued_date,omitempty"`

	// DpcCategory 33: DPC適用区分
	DpcCategory *string `json:"dpc_category,omitempty"`

	// Fullname 37: 基本漢字名称
	Fullname *string `json:"fullname,omitempty"`

	// Id DB内のユニークID
	Id *int `json:"id,omitempty"`

	// MasterType 2: マスター種別 ('T'固定)
	MasterType *string `json:"master_type,omitempty"`

	// MaxAge 16: 上限年齢
	MaxAge *string `json:"max_age,omitempty"`

	// MaxPoints 24: 上限点数
	MaxPoints *int `json:"max_points,omitempty"`

	// MaxPriceFlag 23: 上限価格
	MaxPriceFlag *string `json:"max_price_flag,omitempty"`

	// MinAge 15: 下限年齢
	MinAge *string `json:"min_age,omitempty"`

	// NameKana 7: カナ名称
	NameKana *string `json:"name_kana,omitempty"`

	// NameKanaLen 6: カナ有効桁数
	NameKanaLen *int `json:"name_kana_len,omitempty"`

	// NameKanaUpdateFlag 20: カナ名称変更区分
	NameKanaUpdateFlag *string `json:"name_kana_update_flag,omitempty"`

	// NameKanji 5: 漢字名称
	NameKanji *string `json:"name_kanji,omitempty"`

	// NameKanjiLen 4: 漢字有効桁数
	NameKanjiLen *int `json:"name_kanji_len,omitempty"`

	// NameKanjiUpdateFlag 19: 漢字名称変更区分
	NameKanjiUpdateFlag *string `json:"name_kanji_update_flag,omitempty"`

	// OldPrice 18: 旧金額
	OldPrice *float32 `json:"old_price,omitempty"`

	// OldPriceType 17: 金額種別（旧金額）
	OldPriceType *string `json:"old_price_type,omitempty"`

	// OxygenCategory 21: 酸素等区分
	OxygenCategory *string `json:"oxygen_category,omitempty"`

	// Price 12: 新又は現金額
	Price *float32 `json:"price,omitempty"`

	// PriceType 11: 金額種別（新又は現金額） (1:金額, 2:購入価格, 5:%加算, 9:乗算割合)
	PriceType *string `json:"price_type,omitempty"`

	// PublishOrder 26: 公表順序番号
	PublishOrder *int `json:"publish_order,omitempty"`

	// RelatedCode 27: 廃止・新設関連
	RelatedCode *string `json:"related_code,omitempty"`

	// RemanufacturedDeviceCategory 38: 再製造単回使用医療機器
	RemanufacturedDeviceCategory *string `json:"remanufactured_device_category,omitempty"`

	// Reserved1 13: 予備
	Reserved1 *string `json:"reserved_1,omitempty"`

	// Reserved2 25: 予備
	Reserved2 *string `json:"reserved_2,omitempty"`

	// Reserved3 34: 予備
	Reserved3 *string `json:"reserved_3,omitempty"`

	// Reserved4 35: 予備
	Reserved4 *string `json:"reserved_4,omitempty"`

	// Reserved5 36: 予備
	Reserved5 *string `json:"reserved_5,omitempty"`

	// SectionNumber 32: 区分番号
	SectionNumber *string `json:"section_number,omitempty"`

	// TransitionalDate 29: 経過措置年月日 (YYYYMMDD)
	TransitionalDate *string `json:"transitional_date,omitempty"`

	// UnitCode 8: 単位コード
	UnitCode *string `json:"unit_code,omitempty"`

	// UnitNameKanji 10: 単位漢字名称
	UnitNameKanji *string `json:"unit_name_kanji,omitempty"`

	// UnitNameKanjiLen 9: 単位漢字有効桁数
	UnitNameKanjiLen *int `json:"unit_name_kanji_len,omitempty"`

	// UpdateCategory 1: 変更区分 (0:無変更, 1:抹消, 3:新規, 5:変更, 9:廃止)
	UpdateCategory *string `json:"update_category,omitempty"`

	// UpdateDate 28: 変更年月日 (YYYYMMDD)
	UpdateDate *string    `json:"update_date,omitempty"`
	UpdatedAt  *time.Time `json:"updated_at,omitempty"`
}

// GetCommentsRelatedParams defines parameters for GetCommentsRelated.
type GetCommentsRelatedParams struct {
	// ActCode 診療(調剤)行為コード (9桁)
	ActCode string `form:"act_code" json:"act_code"`
}

// GetCommentsSearchCodeParams defines parameters for GetCommentsSearchCode.
type GetCommentsSearchCodeParams struct {
	// Q コメントコード（完全一致）
	Q string `form:"q" json:"q"`
}

// GetCommentsSearchNameParams defines parameters for GetCommentsSearchName.
type GetCommentsSearchNameParams struct {
	// Q 検索キーワード（部分一致）
	Q string `form:"q" json:"q"`
}

// GetDevicesSearchCodeParams defines parameters for GetDevicesSearchCode.
type GetDevicesSearchCodeParams struct {
	// Q 特定器材コード（完全一致）
	Q string `form:"q" json:"q"`
}

// GetDevicesSearchNameParams defines parameters for GetDevicesSearchName.
type GetDevicesSearchNameParams struct {
	// Q 検索キーワード（部分一致）
	Q string `form:"q" json:"q"`
}

// GetDiseasesSearchCodeParams defines parameters for GetDiseasesSearchCode.
type GetDiseasesSearchCodeParams struct {
	// Q 傷病名コード（完全一致）
	Q string `form:"q" json:"q"`
}

// GetDiseasesSearchIcd10Params defines parameters for GetDiseasesSearchIcd10.
type GetDiseasesSearchIcd10Params struct {
	// Q ICD10コード（完全一致）
	Q string `form:"q" json:"q"`
}

// GetDiseasesSearchNameParams defines parameters for GetDiseasesSearchName.
type GetDiseasesSearchNameParams struct {
	// Q 検索キーワード（部分一致）
	Q string `form:"q" json:"q"`
}

// GetMedicationsSearchCodeParams defines parameters for GetMedicationsSearchCode.
type GetMedicationsSearchCodeParams struct {
	// Q 調剤行為コード（完全一致）
	Q string `form:"q" json:"q"`
}

// GetMedicationsSearchNameParams defines parameters for GetMedicationsSearchName.
type GetMedicationsSearchNameParams struct {
	// Q 検索キーワード（部分一致）
	Q string `form:"q" json:"q"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 全件取得
	// (GET /comments)
	GetComments(c *gin.Context)
	// 関連コメント検索
	// (GET /comments/related)
	GetCommentsRelated(c *gin.Context, params GetCommentsRelatedParams)
	// コメントコード検索
	// (GET /comments/search/code)
	GetCommentsSearchCode(c *gin.Context, params GetCommentsSearchCodeParams)
	// 名称検索
	// (GET /comments/search/name)
	GetCommentsSearchName(c *gin.Context, params GetCommentsSearchNameParams)
	// 全件取得
	// (GET /devices)
	GetDevices(c *gin.Context)
	// 特定器材コード検索
	// (GET /devices/search/code)
	GetDevicesSearchCode(c *gin.Context, params GetDevicesSearchCodeParams)
	// 名称検索
	// (GET /devices/search/name)
	GetDevicesSearchName(c *gin.Context, params GetDevicesSearchNameParams)
	// 全件取得
	// (GET /diseases)
	GetDiseases(c *gin.Context)
	// 傷病名コード検索
	// (GET /diseases/search/code)
	GetDiseasesSearchCode(c *gin.Context, params GetDiseasesSearchCodeParams)
	// ICD10検索
	// (GET /diseases/search/icd10)
	GetDiseasesSearchIcd10(c *gin.Context, params GetDiseasesSearchIcd10Params)
	// 名称検索
	// (GET /diseases/search/name)
	GetDiseasesSearchName(c *gin.Context, params GetDiseasesSearchNameParams)
	// 調剤行為コード検索
	// (GET /medications/search/code)
	GetMedicationsSearchCode(c *gin.Context, params GetMedicationsSearchCodeParams)
	// 名称検索
	// (GET /medications/search/name)
	GetMedicationsSearchName(c *gin.Context, params GetMedicationsSearchNameParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetComments operation middleware
func (siw *ServerInterfaceWrapper) GetComments(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetComments(c)
}

// GetCommentsRelated operation middleware
func (siw *ServerInterfaceWrapper) GetCommentsRelated(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCommentsRelatedParams

	// ------------- Required query parameter "act_code" -------------

	if paramValue := c.Query("act_code"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument act_code is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "act_code", c.Request.URL.Query(), &params.ActCode)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter act_code: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCommentsRelated(c, params)
}

// GetCommentsSearchCode operation middleware
func (siw *ServerInterfaceWrapper) GetCommentsSearchCode(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCommentsSearchCodeParams

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument q is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCommentsSearchCode(c, params)
}

// GetCommentsSearchName operation middleware
func (siw *ServerInterfaceWrapper) GetCommentsSearchName(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCommentsSearchNameParams

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument q is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCommentsSearchName(c, params)
}

// GetDevices operation middleware
func (siw *ServerInterfaceWrapper) GetDevices(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDevices(c)
}

// GetDevicesSearchCode operation middleware
func (siw *ServerInterfaceWrapper) GetDevicesSearchCode(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDevicesSearchCodeParams

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument q is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDevicesSearchCode(c, params)
}

// GetDevicesSearchName operation middleware
func (siw *ServerInterfaceWrapper) GetDevicesSearchName(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDevicesSearchNameParams

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument q is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDevicesSearchName(c, params)
}

// GetDiseases operation middleware
func (siw *ServerInterfaceWrapper) GetDiseases(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDiseases(c)
}

// GetDiseasesSearchCode operation middleware
func (siw *ServerInterfaceWrapper) GetDiseasesSearchCode(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDiseasesSearchCodeParams

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument q is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDiseasesSearchCode(c, params)
}

// GetDiseasesSearchIcd10 operation middleware
func (siw *ServerInterfaceWrapper) GetDiseasesSearchIcd10(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDiseasesSearchIcd10Params

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument q is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDiseasesSearchIcd10(c, params)
}

// GetDiseasesSearchName operation middleware
func (siw *ServerInterfaceWrapper) GetDiseasesSearchName(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDiseasesSearchNameParams

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument q is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDiseasesSearchName(c, params)
}

// GetMedicationsSearchCode operation middleware
func (siw *ServerInterfaceWrapper) GetMedicationsSearchCode(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMedicationsSearchCodeParams

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument q is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMedicationsSearchCode(c, params)
}

// GetMedicationsSearchName operation middleware
func (siw *ServerInterfaceWrapper) GetMedicationsSearchName(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMedicationsSearchNameParams

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument q is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMedicationsSearchName(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/comments", wrapper.GetComments)
	router.GET(options.BaseURL+"/comments/related", wrapper.GetCommentsRelated)
	router.GET(options.BaseURL+"/comments/search/code", wrapper.GetCommentsSearchCode)
	router.GET(options.BaseURL+"/comments/search/name", wrapper.GetCommentsSearchName)
	router.GET(options.BaseURL+"/devices", wrapper.GetDevices)
	router.GET(options.BaseURL+"/devices/search/code", wrapper.GetDevicesSearchCode)
	router.GET(options.BaseURL+"/devices/search/name", wrapper.GetDevicesSearchName)
	router.GET(options.BaseURL+"/diseases", wrapper.GetDiseases)
	router.GET(options.BaseURL+"/diseases/search/code", wrapper.GetDiseasesSearchCode)
	router.GET(options.BaseURL+"/diseases/search/icd10", wrapper.GetDiseasesSearchIcd10)
	router.GET(options.BaseURL+"/diseases/search/name", wrapper.GetDiseasesSearchName)
	router.GET(options.BaseURL+"/medications/search/code", wrapper.GetMedicationsSearchCode)
	router.GET(options.BaseURL+"/medications/search/name", wrapper.GetMedicationsSearchName)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcX1Mbx7L/Klt7763YVSRIK/7uWy5U3eIht1LJeXGdSm0t0gDrI+0quysXrpSrWCk4",
	"EgaDOTaYmMTIhoCNwfYxSQwI+7ucZXalJ77Cqdk/+rczOyth47iSN6GZ6enp7un+dU+L79ikkskqMpB1",
	"jeW/Y7XkFMiIzscRJZMBso4+ZlUlC1RdAs5AUtTBpKJeR59TQEuqUlaXFJnl2QTPwPkjWLzJXPpk6BP4",
	"4Aju/3iZ7WH161nA8qymq5I8yd7oYZNKCgSXcwmeMfOvzELZLLwyC0Xnc8UslJhLw1bZwFNSgaiDlCA6",
	"jE4oagZ9YlOiDj7VpQzArUlJWlKRdUnOgZSAZmJY4XgGHhesvUfw8MBaL1qrW8ylK1euXPnii9FRLCNS",
	"Kkhl9H/hzVnT2DcLv5iFW+gs+edjo43VkqyDSaCi5RlR04EquAMBbnjGLPxs5g/N/FuzULF39mFxi7n0",
	"yUiYjGUxA4R/iLIYpDeM5LxrFubg0oK9/SJ0tZAGcpDCkE/BWi/BuUOrbFj3XmAP5hO6KgWpDPKMVXkE",
	"91bpfFyV8IwM+CSojGRFXQcqhkQfku4dV7Rm4RWOi2xuPC1pU4KipoCK0U8fz8DZZ9XyTm3jJjxatO89",
	"hYu/Y7lQQRJIWV0AKUkXJHlCEeL4g8XjPPPvOxshB8KRyioahlTMIeUo7IlZ2Dg9WbBP9iPS5AjsJRDN",
	"ckfscQT2OIdUd+wlCOz1I5qPOmIvQWCvzyHVHXt9BPYGEc3HHbHXR2BvwCEVjT0NqNdASohjyAzxzOlR",
	"EebXcPZfX8lhVg5HWpnAXJv+SCv7MCsHIq3sx6wcjLRyALMymoQGMSujSWgIE1BjYSs1kAZJNFMgh2Qu",
	"xjM147U19zOsLDYH1+refVjcwpNVJTEtyEqQGlLY65nazON2D9dYncuiiBrCUZxn4GbJenDgQ4UYb39f",
	"dr/qYeK8NXdo/VbsYRK8tfKi+stiD9PP+6PDvBuUL4fsTAjojW0jBnSXXCfI4kb9G2X8KkjqiIqHor4C",
	"adHlpB1NiUld8OFQgAc06ERAcXxcxc9IpSTXBIg0UhlJ09qtJDBtXBXl5JQg5zLjAL9VUkwnc2lHuUrO",
	"BYZBH5N0z0tmx5+gg2mdMEH2jxTGbwP4CSpInwP8+csJiC54REkHmTA5yYosZMXrzilVIGqu1jHTdGlC",
	"SjpmUcd9QeQh6hIipOmintPIYm1BKMQjaa6/wI5hLm7YFSPu0bg3nSgGd3dGJQ2IGsDcmZSSpfg9BCqs",
	"22Xk9xw3gzOFOhnvWBNpcZJgkrh0BWU7+d/t1Vm4tFBPVd5ZjgJkHTnh0MvfPskHG0GbDcykHdlboGVB",
	"ElmpkHJ1EW4e7Yuom0RIxPoCiRjhVjvsgenklChPAgGvMoRaXYWdHm1aiw/suzuhmguQjXAiZ0FGlMVJ",
	"4LiAhqcIAnyXF3u/bC/dJIdUKZmKx7CgbYBnxkZGP43HPo2HLKRy7c7j8DjV24Ajb8DRNyC50kxWUfWw",
	"HHzxdrVSClW9JCdzqjieBtFsNDidyrys5VBwBIKS0ylQ6/TtT7W1o+ruLetlHm6ukH1PK1EqC5qgpDEF",
	"Bmt1u+6CXCsyC/fMfNnMb5qFXfvuS+unLdPYhxsHcKmoq7kmVzOuKGkgyt3VHnAnykiTqhvMIhh/Yohn",
	"7O3jankezhaj3YIGfV1UJ4HjS/9bBRMsz/5Xb6OK1euVsHr96OEXEXwvGihkNCS4btj3tii1iGY/G6hm",
	"YEnRiiOR/HFINQel902B6Fx1nWECqQgFHjHyGXCloIGmjeHDI2v9Wfc1oX4CrUhVKuopVATlQYoQYfqa",
	"7Do0tIQm431dJ+P93SbjEQsAfQSZNGfclLSakjsHQaskT6aBkNOAMKGo41IqBUKRH7Lhhfv2rWenJ2/t",
	"uzv2LwZCD0RPjCVPM4JQXBTMPO3SIdz/0V55Y+Uf23sl+PxN9WU5hKV26jR2Ok26O0+fE4H0+f3lzF+A",
	"lJcXYaD/JBAaOW9ogkgC7dWnb2Fps1qet/NH7x634yBtt3goGAPfTaQWpwVxkrTDtJBVJO85CPdOMS1k",
	"VSkZYoyZuvrwSCB0QT3IRyJfn90pdddQafO9dDmUuiQTZRkSswfP/QIz0PELzPkCdP/532r6Ir/VdBCO",
	"lXTKNcimUU9fzaMhFRbiYm+hkyxQZxHJtz8d4eryrYiCghVChmOUcdp6jjKeoIxT0EGcAg/iFHwQH6SM",
	"D1HGh8PHKcfnKOLlKOLlaPQp4uUo4uUo4uUo4uUo4uUo4uUo4qUcL0ERb4Ii3gRFvB8Aura+7ZCH8YLT",
	"VVHWHKQjpsmYICdLIeV2Z7TVr9PmkKuI7wFmvicI+TVC0GLaRZLpUXDN894RwWQwHYOHB7WTR3Buw95f",
	"DakoZ7NATknT5LoHklBxq1reIRc6iMDVzSLg2o7109J7641xRBWWznCtjJBhZoTqbiLWaZtNKpsMYS6R",
	"4JnRL0dqxhP77g5ZTRO5dBrZO4bAIM+4JQMa2PkQ/T5/C+v3aUL1wSrx6eu52tqSa8SkxQ3YHyzBu+vt",
	"/CEJsQXzgmAC6RI5fVO2Nir4Cp9MOIHz7nwr9AR/dLAdrBU380Tzmh8BMg9WYZq5oh2wBcYHK1PW6nbt",
	"hzu18gLb03BkE2lF1BvEwlB/8FnDJederbNKsb7BWQVbC1Cmr0+Glp24OM/UZl/bBxv2Xol8TtIZOZ6x",
	"Vl7AxaJpPLcX33Rw2NCDxoMHDexyVikxl+K8+0cPw/HVVxU4u+Xe0x6mn/8fN+z1MMP86eEqCoClf8Gl",
	"4uVuOuUGOuiUC6uzcoN+5DALx9bKi+rOXm3lUW3mMb56mRHl3ISY1HMqikW0GJcY4hl4c6H6+KQ2swEX",
	"7sMHP7u1RDh/bK/lrScP4dpOx0XdRLdFXa7rom6ir9sOq0R/tx1WiYHwnqX2kkrbas7vISYDJCwuDrZc",
	"2b/O14zb1u2n9sl+5KafZjAdfClauH96Ev7Wj8HbmNcahw7NaRNgefDBpoka1X//Uduzhj5Ee9YN5yF2",
	"AtPoBm//aN99COcOYGHBXjdMY9+9+s2w7KxSbEHkM0ZL8/qMUX+EOquUzPyytbluHyB3BRdX4JtV01gz",
	"87dM46GZR/Q//3LMNLbRlzN5xLukpxGrwW1dMp9/Ocb2sNeAqnlq+yz2WcwJVFkgi1kJXSXnK6eFaMqB",
	"db1e75Xzh/eC2nrslgM07Ym4X5+Bm9vxWCx2evybf4JV03hTZxllVk7ddCzF8uz/AX3E385xGFlF1ty0",
	"i4s5mT5KDrwfGIjZbNoruvZe9Rqm3Hdc9EnSQUajPff6P1doaFlUVfG6q+S2V/PiEpx76BiElstkRHQN",
	"WDi7Uz+YM1SXVq8XiYhSq+4c2Wt5/0Hhezh/XF15Bv9pmMZT03iC8gHfY5jGrhulTo/vm8YdM18y8/OO",
	"CTTkbhVm4cZLM7/cmZC/8phE+lbFDNCBqrH83/G8XnLfQC63PYI0ckkJzf02B9TrrIv5kDz9TkWkzm9z",
	"kopEoqs50NOkq/Y7980F6r7eZNmBDfSwfS5HbRehcMdppy47xv/29PWCtfe4zWJcTbaozrmabdajAVFN",
	"TvX6QQVrQUjsvp20//jFNLY9zxHREr52NhxxNRVqDNj9zipFuD+PrsPrmeoPBy4extnDt39YQ7ggA8CK",
	"L8wG/JoD1gaa4YCj54em8bw5RzSNXTO/5+zy3DON/DJc2jXzM62cLHdjL/8vZqj24tFtZeKsUqwVdmDx",
	"5l/2QrEXrwulyUDcTIQcj1vwxbnj8ai320VIFluAfXex2RNcJ84VWz2N7Fw92UX3rdjtPmbfel6NnuPi",
	"YGWJuUed+1mE2Zs87IxR97zBKnCI//VZW+7CmP6UjvcDGhPGC7tdVmQ33GiJPL8P9ve6CCk3tcC+K7/r",
	"sR/J8Q66jjf4I4noXtfbLrrbDW72MfvcLhR4npsRkB3ulviqd3r/ibofGxmNx86r8DFnC4rGW3f6S9tR",
	"te3ILUzBoVEU22BtzhjNje/t0TUkfjYsb7kbQ/lTxtALdg6BsNlolOwIh2PbbyM7iEZvcAdBAbvlx+wp",
	"mjqkL0b7WAlSjCHUfzQTdE3rrFJ00bZZOHbdxlmlFOIzWlla7tJ8/pSe48LNp815uP9k4BqhKFlw5Iws",
	"YLe2csteOzLzvzoyXzILFbaHzalplmendD3L9/amlaSYnlI0nR+KDcXYG9/c+E8AAAD//4pENLrTSAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
