package batch

import (
	"medical_master/internal/model"

	"gorm.io/gorm"
)

func ImportMedications(db *gorm.DB) {
	importCsv(db, 65, "csv/medication/m20250307.csv", func(record []string) model.Medication {
		return model.Medication{
			UpdateCategory:             record[0],
			MasterType:                 record[1],
			Code:                       record[2],
			NameKanjiLen:               parseInt(record[3]),
			NameKanji:                  record[4],
			NameKanaLen:                parseInt(record[5]),
			NameKana:                   record[6],
			UnitCode:                   record[7],
			UnitNameKanjiLen:           parseInt(record[8]),
			UnitNameKanji:              record[9],
			PriceType:                  record[10],
			Price:                      parseFloat(record[11]),
			Reserved1:                  record[12],
			AgeAdditionCategory:        record[13],
			MinAge:                     record[14],
			MaxAge:                     record[15],
			OldPriceType:               record[16],
			OldPrice:                   parseFloat(record[17]),
			NameKanjiUpdateFlag:        record[18],
			NameKanaUpdateFlag:         record[19],
			Reserved2:                  record[20],
			Reserved3:                  record[21],
			MaxPriceFlag:               record[22],
			MaxPoints:                  parseInt(record[23]),
			Reserved4:                  record[24],
			PublishOrder:               parseInt(record[25]),
			RelatedCode:                record[26],
			UpdateDate:                 record[27],
			TransitionalDate:           record[28],
			DiscontinuedDate:           record[29],
			MedicationSectionNumber:    record[30],
			Reserved5:                  record[31],
			Reserved6:                  record[32],
			Reserved7:                  record[33],
			Reserved8:                  record[34],
			Reserved9:                  record[35],
			Reserved10:                 record[36],
			Reserved11:                 record[37],
			Reserved12:                 record[38],
			Reserved13:                 record[39],
			Reserved14:                 record[40],
			Reserved15:                 record[41],
			Reserved16:                 record[42],
			Reserved17:                 record[43],
			Reserved18:                 record[44],
			Reserved19:                 record[45],
			Reserved20:                 record[46],
			Reserved21:                 record[47],
			Reserved22:                 record[48],
			Reserved23:                 record[49],
			Reserved24:                 record[50],
			Reserved25:                 record[51],
			Reserved26:                 record[52],
			Reserved27:                 record[53],
			Reserved28:                 record[54],
			Reserved29:                 record[55],
			Reserved30:                 record[56],
			Reserved31:                 record[57],
			PriceTablePrice:            parseFloat(record[58]),
			ImportDate:                 record[59],
			Reserved32:                 record[60],
			MedicationManagementNumber: record[61],
			MedicationMigrationNumber:  record[62],
			MedicationMigrationFlag:    record[63],
			MedicationMigrationUpdate:  record[64],
		}
	})
}
